name: alloy-example

include:
  - ./grafana.yaml
  - ./databases.yaml

services:
  alloy:
    image: grafana/alloy:v1.19.2
    pull_policy: always
    restart: on-failure
    volumes:
      - ./config/alloy:/etc/alloy
    environment:
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      PYROSCOPE_HOST: pyroscope:4040
      GRAFANA_CLOUD_OTLP_ENDPOINT: https://otlp-gateway-dev-us-central-0.grafana-dev.net/otlp
      GRAFANA_CLOUD_OTLP_USERNAME: ${GRAFANA_CLOUD_OTLP_USERNAME:-}
      GRAFANA_CLOUD_OTLP_API_TOKEN: ${GRAFANA_CLOUD_OTLP_API_TOKEN:-}
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
