services:
  mimir:
    image: grafana/mimir:3.2.0
    restart: on-failure
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ./config/mimir:/etc/mimir-config
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.7.7
    restart: on-failure
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:3.0.3
    restart: on-failure
    command:
      - "-config.file=/etc/tempo-config/tempo.yaml"
    volumes:
      - ./config/tempo:/etc/tempo-config
    ports:
      - "3200:3200"
      # - "4317:4317"

  pyroscope:
    image: grafana/pyroscope:2.3.1
    restart: on-failure
    ports:
      - "4040:4040"
