services:
  grafana:
    image: grafana/grafana:13.2.1
    restart: on-failure
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana-config
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboardprovisioner:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthz" ]
      interval: 1s
      timeout: 10s
      retries: 5
    env_file:
      # Use this optional env file to add any secrets required by data sources you can add to config/grafana/datasources
      - path: ~/.grafana_dev_datasources
        required: false
