{
 "title": "MMR",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "var_latest_song_title",
    "label": "Current Song Title",
    "query": {
     "query": "query_result(topk(1,  sum by (song_artist, song_title) (    increase(itgmania_current_song_note_hits[15s])  )))"
    }
   },
   {
    "name": "var_latest_song_difficulty",
    "query": {
     "query": "query_result(topk(1,  sum by (song_artist, song_title, difficulty) (    increase(itgmania_current_song_note_hits[15s])  )))"
    }
   },
   {
    "name": "latest_song_difficulty_meter",
    "query": {
     "query": "query_result(topk(1,  sum by (song_artist, song_title, difficulty,meter) (    increase(itgmania_current_song_note_hits[15s])  )))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Combo in last hour",
   "type": "stat",
   "description": "Displays the highest combo achieved in any single ITGMania song played during the last hour",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(itgmania_max_combo[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Hits per second in the last hour ",
   "type": "stat",
   "description": "Displays the per-second rate for each successful note judgment type (e.g., Fantastic, Excellent, Great), aggregated across all songs and contexts. 'Miss' judgments are excluded.",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  (sum by (tns) (rate(itgmania_note_hit_timing_histogram_count{tns!=\"Miss\"}[5s])))\n  [1h:5s]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Score in the last hour",
   "type": "stat",
   "description": "Highest score achieved in the last hour",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, max_over_time(itgmania_current_score[1h]))",
     "legendFormat": "{{song_title}} - {{difficulty}} ({{meter}})"
    }
   ]
  },
  {
   "title": "How far from perfect?",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(itgmania_note_hit_timing_histogram_bucket{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Song", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Max Combo in current song",
   "type": "stat",
   "description": "Displays the highest combo achieved in the current song.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "itgmania_max_combo", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Combo",
   "type": "stat",
   "description": "Displays the highest combo achieved in the current song.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(itgmania_current_combo{song_title=~\"$var_latest_song_title\", meter=\"$latest_song_difficulty_meter\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hits per second",
   "type": "stat",
   "description": "Displays the per-second rate for each successful note judgment type (e.g., Fantastic, Excellent, Great), aggregated across all songs and contexts. 'Miss' judgments are excluded.",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tns) (rate(itgmania_note_hit_timing_histogram_count{tns!=\"Miss\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Note Hits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "itgmania_current_song_note_hits{song_title=~\"${var_latest_song_title}\", meter=\"$latest_song_difficulty_meter\"}",
     "legendFormat": "{{tns}}"
    }
   ]
  },
  {
   "title": "Current Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "itgmania_current_score{song_title=~\"$var_latest_song_title\",meter=\"$latest_song_difficulty_meter\"}",
     "legendFormat": "{{song_title}} - {{difficulty}} ({{meter}})"
    }
   ]
  },
  {
   "title": "Life Bar",
   "type": "gauge",
   "description": "Displays the current ITGMania life bar level as a percentage (0-100).",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "itgmania_life_bar", "legendFormat": "__auto" }
   ]
  },
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average FPS",
   "type": "stat",
   "description": "Shows the average rendering performance (FPS) of the ITGMania client, calculated across the dashboard's current time period",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(itgmania_fps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 6, "y": 17 },
   "targets": [
    {
     "filters": [
      { "id": "0569b6b2", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "itgmania" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "10ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "6cd486db064d66c095aea4279fc4cc66",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "ITGMania Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"itgmania\"}"
    }
   ]
  }
 ]
}